[package]
name = "bismuth"
version = "0.1.0"
authors = [
  "Michael Meyer <meyerz.michael@gmail.com>",
  "Hugh Harris <dhharris9@gmail.com>",
]

[lib]
test = false
doctest = false

[profile.test]
panic = 'unwind'
debug-assertions = true

[dependencies]
glium = "*"
rand = "0.3"
